name: Publish the new version of the course to the API
on:
  push:
    branches:
      - main
      - anchor-config
  workflow_dispatch:

env:
  API_KEY: "${{ secrets.API_KEY }}"
  API_URL: https://develop.api.kibo.school
  REPO_PATH: kiboschool/course-intro-to-data-science
jobs:
  deploy:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v2

      - name: publish
        run: |
          curl --request PUT --url $API_URL/api/latest/courses -H 'Authorization: SharedKey $API_KEY' -H 'Content-Type: application/json' --data '{"github_path": "'"$REPO_PATH"'"}'
